language: go

go:
  - 1.6

install:
  - go get github.com/jinzhu/gorm
  - go get github.com/lib/pq
  - go get github.com/zenazn/goji
  - go get github.com/zenazn/goji/web
  - export FILE=go_appengine_sdk_linux_amd64-$(curl https://appengine.google.com/api/updatecheck | grep release | grep -o '[0-9\.]*').zip
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
  - unzip -q $FILE

before_script:
  - psql -c 'create database wikin_test;' -U postgres
  - psql -f db/structure.sql wikin_test

script:
    - DATABASE_URL="dbname=wikin_test sslmode=disable" ./go_appengine/goapp test
