language: go

go:
  - 1.7

install:
  - go get github.com/jinzhu/gorm
  - go get github.com/lib/pq
  - go get github.com/labstack/echo
  - go get github.com/dgrijalva/jwt-go

before_script:
  - psql -c 'create database wikin_test;' -U postgres
  - psql -f db/structure.sql wikin_test
